image: docker:latest

test:
  stage: test
  image: golang:1.9-alpine
  script:
    - apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/main nodejs nodejs-npm
    - cd testdata
    - npm install bson
    - node createTestData.js
    - go test
  cache:
    untracked: true
    paths:
      - testdata/node_modules/

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - tags

