image: docker:latest

test:
  stage: test
  image: golang:1.9-alpine
  script:
    - apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/main nodejs nodejs-npm git
    - cd testdata
    - npm install bson
    - node createTestData.js
    - cd ..
    - ./bin/git-config.sh "gitlab-ci-token:$CI_JOB_TOKEN"
    - go get gitlab.com/cgps/bsonkit
    - go test
  cache:
    untracked: true
    paths:
      - testdata/node_modules/

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build
        --pull
        --build-arg http_proxy=$http_proxy
        --build-arg https_proxy=$https_proxy
        --build-arg ftp_proxy=$https_proxy
        --build-arg git_credentials="gitlab-ci-token:$CI_JOB_TOKEN"
        -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - tags
